/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Pais;

/**
 *
 * @author contr
 */
public class ModificarJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form ModificarJPanel
     */
    public ModificarJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        modificarJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreJTextField = new javax.swing.JTextField();
        numeroInfeJTextField = new javax.swing.JTextField();
        numeroMuerJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        busquedaJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jTextField4.setText("jTextField4");

        setBackground(new java.awt.Color(0, 17, 48));
        setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(13, 13, 47));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        modificarJButton.setBackground(new java.awt.Color(13, 13, 47));
        modificarJButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        modificarJButton.setForeground(new java.awt.Color(255, 255, 255));
        modificarJButton.setText("Modificar");
        modificarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de infectados:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de muertos:");

        nombreJTextField.setBackground(new java.awt.Color(204, 204, 204));
        nombreJTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nombreJTextField.setForeground(new java.awt.Color(0, 0, 0));

        numeroInfeJTextField.setBackground(new java.awt.Color(204, 204, 204));
        numeroInfeJTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        numeroInfeJTextField.setForeground(new java.awt.Color(0, 0, 0));

        numeroMuerJTextField.setBackground(new java.awt.Color(204, 204, 204));
        numeroMuerJTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        numeroMuerJTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modificar Pais");

        busquedaJTextField.setBackground(new java.awt.Color(204, 204, 204));
        busquedaJTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        busquedaJTextField.setForeground(new java.awt.Color(0, 0, 0));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(busquedaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificarJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroMuerJTextField)
                            .addComponent(numeroInfeJTextField)
                            .addComponent(nombreJTextField))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busquedaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(numeroInfeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroMuerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(modificarJButton))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            inicio();
        } catch (IOException ex) {
            Logger.getLogger(ModificarJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modificarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarJButtonActionPerformed
        modificar();
    }//GEN-LAST:event_modificarJButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            buscar();
        } catch (IOException ex) {
            Logger.getLogger(ModificarJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedaJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton modificarJButton;
    private javax.swing.JTextField nombreJTextField;
    private javax.swing.JTextField numeroInfeJTextField;
    private javax.swing.JTextField numeroMuerJTextField;
    // End of variables declaration//GEN-END:variables
       private void inicio() throws IOException {
        principal.volverAInicio(this);
    }

    private Pais buscar() throws IOException {
        String nombreBusqueda = busquedaJTextField.getText();
        Pais pais = principal.paises.buscarPorNombre(nombreBusqueda);
        principal.paises.eliminarPais(pais);
        principal.persistencia.guardar(principal.paises);
        if (pais != null) {
            nombreJTextField.setText(pais.getNombre());
            numeroInfeJTextField.setText(String.valueOf(pais.getNumeroContagiados()));
            numeroMuerJTextField.setText(String.valueOf(pais.getNumeroMuertos()));
            
           
        } else {
            JOptionPane.showMessageDialog(this, "Error al buscar el pais", "No se encontro el pais " + nombreBusqueda, JOptionPane.INFORMATION_MESSAGE);
        }
        busquedaJTextField.setText("");
        return pais;

    }

    private void modificar() {

        try {
            String nombre;
            int numeroInf, numeroMuer;
            nombre = nombreJTextField.getText();
            numeroInf = Integer.parseInt(numeroInfeJTextField.getText());
            numeroMuer = Integer.parseInt(numeroMuerJTextField.getText());
            Pais paisModificado = new Pais(nombre, numeroInf, numeroMuer);
            principal.paises.agregarPais(paisModificado);
            principal.persistencia.guardar(principal.paises);
            limpiar();
        } catch (Exception NumberFormatException) {
            JOptionPane.showMessageDialog(this, "Error al cmodificar el pais", "No se modifico el pais ", JOptionPane.INFORMATION_MESSAGE);
        
        }

    }

    private void limpiar() {
        nombreJTextField.setText("");
        numeroInfeJTextField.setText("");
        numeroMuerJTextField.setText("");
    }
}
